FROM python:3.13-slim-bookworm

RUN apt-get update
RUN apt-get install -y libpq-dev python3-dev build-essential

WORKDIR /app
COPY requirements.txt .
RUN pip install -r requirements.txt
RUN rm -rf /var/lib/apt/lists/*

COPY . .
RUN rm -rf frontend

EXPOSE 8000
CMD ["python", "main.py"]