FROM node:22-bookworm-slim

RUN apt-get update && apt-get install -y \
    python3-pip \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY frontend/ .
RUN npm install --production

EXPOSE 3000
CMD ["npm", "start"]